title: Test video index
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://hkdigitalmemory.github.io/video-index-test-new

aux_links:
  Template Repository: https://hkdigitalmemory.github.io/video-index-test-new

permalink: pretty

# https://just-the-docs.com/docs/configuration/#callouts
callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Note
    color: yellow

# Enable or disable the site search
search_enabled: true
